services:
  frontend:
    build: .
    env_file:
      - .env
    restart: unless-stopped

    networks:
      - traefik-public

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"

      # Service
      - "traefik.http.services.frontend-spravki.loadbalancer.server.port=80"

      # Middleware
      - "traefik.http.middlewares.frontend-spravki-strip.stripprefix.prefixes=/spravki"
      - "traefik.http.middlewares.frontend-spravki-slash.redirectregex.regex=^https?://([^/]+)/spravki$$"
      - "traefik.http.middlewares.frontend-spravki-slash.redirectregex.replacement=https://$${1}/spravki/"
      - "traefik.http.middlewares.frontend-spravki-slash.redirectregex.permanent=true"

      # HTTP Router
      - "traefik.http.routers.frontend-spravki.rule=Host(`sesc-it-team.ru`) && PathPrefix(`/spravki`)"
      - "traefik.http.routers.frontend-spravki.entrypoints=web"
      - "traefik.http.routers.frontend-spravki.middlewares=frontend-spravki-slash,frontend-spravki-strip"
      - "traefik.http.routers.frontend-spravki.service=frontend-spravki"

      # HTTPS Router
      - "traefik.http.routers.frontend-spravki-secure.rule=Host(`sesc-it-team.ru`) && PathPrefix(`/spravki`)"
      - "traefik.http.routers.frontend-spravki-secure.entrypoints=websecure"
      - "traefik.http.routers.frontend-spravki-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.frontend-spravki-secure.middlewares=frontend-spravki-slash,frontend-spravki-strip"
      - "traefik.http.routers.frontend-spravki-secure.service=frontend-spravki"

networks:
  traefik-public:
    external: true
    name: traefik-public
